version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tanstack-query-demo-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tanstack_query_demo
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
